from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from . import views
from .views import CreateOrderAPIView, VerifyPaymentAPIView, ContactAPIView

# The router automatically generates the API URLs for our ViewSets
router = DefaultRouter()
router.register(r'profiles', views.ProfileViewSet)
router.register(r'tests', views.MedicalTestViewSet)
router.register(r'parameters', views.TestParameterViewSet)
router.register(r'bookings', views.BookingViewSet)

urlpatterns = [
    # This includes all the routes generated by the router under the 'api/' path
    path('api/login/', obtain_auth_token, name='api_token_auth'),
    path('api/', include(router.urls)),
    path('api/create-order/', CreateOrderAPIView.as_view(), name='create-order'),
    path('api/verify-payment/', VerifyPaymentAPIView.as_view(),
         name='verify-payment'),
    path('api/contact/', ContactAPIView.as_view(), name='contact'),
]
