from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# The router automatically generates the API URLs for our ViewSets
router = DefaultRouter()
router.register(r'profiles', views.ProfileViewSet)
router.register(r'tests', views.MedicalTestViewSet)
router.register(r'parameters', views.TestParameterViewSet)

urlpatterns = [
    # This includes all the routes generated by the router under the 'api/' path
    path('api/', include(router.urls)),
]
