# Generated by Django 5.2.7 on 2026-05-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tests/images/')),
                ('key_benefits', models.TextField(help_text='Enter key benefits separated by commas')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Gym Profile', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/images/')),
                ('purpose_section', models.TextField()),
                ('benefits_section', models.TextField()),
                ('best_for_section', models.TextField()),
                ('tests', models.ManyToManyField(related_name='profiles', to='shop.medicaltest')),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text="e.g., 'Lipid Profile' or leave blank", max_length=255, null=True)),
                ('name', models.CharField(help_text="e.g., 'Total Cholesterol'", max_length=255)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='shop.medicaltest')),
            ],
        ),
    ]
