# Generated by Django 5.2.7 on 2026-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='tests_included',
            field=models.TextField(blank=True, null=True),
        ),
    ]
