# Generated by Django 5.2.7 on 2026-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
